AWSTemplateFormatVersion: '2010-09-09'
Description: MainTable for data storage

Parameters:
  Environment:
    Type: String
    Description: 'Enter environment name: production/staging/testing/etc.'

Resources:
  DerTisch:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "Highfive-${Environment}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: Org
          AttributeType: S

      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:

        - IndexName: Organisations
          KeySchema:
            - AttributeName: Org
              KeyType: HASH
            - AttributeName: PK
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY

Outputs:
  DerTisch:
    Description: main storage
    Value: !Ref 'DerTisch'
