run:
  skip-dirs:
    - "node_modules"
  skip-files:
    - ".*_test\\.go"

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  #  dupl:
  #    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140

linters:
  enable-all: true
  disable:
    - dupl
    - goconst
    - prealloc
    - gomnd
    - gocognit
    - gocyclo
    - misspell
    - gochecknoglobals
    - funlen