# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.2.3
      hooks:
        - id: check-case-conflict
        - id: check-merge-conflict
        - id: check-symlinks
        - id: check-yaml
          args:
            - --unsafe
        #    - id: end-of-file-fixer
        #    - id: pretty-format-json
        #      args:
        #        - --autofix
        - id: trailing-whitespace
  -  repo: git://github.com/dnephin/pre-commit-golang
     sha: HEAD
     hooks:
       - id: go-fmt

  -   repo: local
      hooks:
        - id: tests
          name: run tests
          entry: make tests
          language: system
          files: tests
          always_run: true
        - id: lint
          name: run linter
          entry: make lint
          language: system
          files: tests
          always_run: true